# Machine Learning

# Notebook set-up

In [1]:
import os 
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import io

sns.set_style('whitegrid')
sns.set_context('notebook')

# Data loading

In [2]:
# Load the data into a dataframe 
df = pd.read_csv('general.csv')

In [3]:
df.head()

cand_id  cycle        c1       c2        c3         c4       c5  \
0  H0AK00089   2010    550.00     0.00      0.00       0.00      0.0   
1  H0AL02087   2012  11727.82     0.00  16964.09       0.00      0.0   
2  H0AL02087   2014  12132.25     0.00  16866.78       0.00      0.0   
3  H0AL03184   2010     14.95  1441.91      0.00    5000.00      0.0   
4  H0AL05163   2010  54616.04  2343.79  71452.12  547321.04  27000.0   

         c6       c7     c8    ...     incumbent  party  primary_votes  \
0    785.00     0.00    0.0    ...             0      D        38673.0   
1      0.00     0.00    0.0    ...             1      R            0.0   
2      0.00     0.00    0.0    ...             1      R            0.0   
3   2293.50     0.00    0.0    ...             0      D            0.0   
4  66857.04  9362.66  249.0    ...             0      R        35746.0   

   runoff_votes  general_votes ge_runoff_election_votes winner total_votes  \
0           0.0        77606.0                      0.0      0    116279.0   
1           0.0       180591.0                      0.0      1    180591.0   
2           0.0       113103.0                      0.0      1    113103.0   
3           0.0        80204.0                      0.0      0     80204.0   
4           0.0       131109.0                      0.0      1    166855.0   

  totalspend  costvote  
0  220001.06  1.892010  
1  694953.98  3.848220  
2  570473.48  5.043840  
3    8750.36  0.109101  
4  780579.65  4.678192  

[5 rows x 27 columns]

In [59]:
df.describe()

cycle            c1             c2            c3            c4  \
count  8213.000000  8.213000e+03    8213.000000  8.213000e+03  8.213000e+03   
mean   2008.950444  1.135745e+05    4061.222854  3.459565e+04  1.051760e+05   
std       3.347703  5.393104e+05   16729.377074  1.621167e+05  6.404058e+05   
min    2004.000000 -2.900000e-01    -390.000000 -1.900000e-01 -7.500000e+02   
25%    2006.000000  0.000000e+00       0.000000  0.000000e+00  0.000000e+00   
50%    2010.000000  0.000000e+00       0.000000  0.000000e+00  0.000000e+00   
75%    2012.000000  3.401606e+04     477.000000  6.238620e+03  5.401690e+03   
max    2014.000000  2.545184e+07  527439.630000  8.283133e+06  2.546524e+07   

                  c5            c6            c7             c8            c9  \
count    8213.000000  8.213000e+03  8.213000e+03    8213.000000   8213.000000   
mean     5801.780386  9.377898e+03  3.864802e+03     179.584555     41.562651   
std     23956.670138  5.808186e+04  2.584147e+04    6404.753425    862.691798   
min         0.000000  0.000000e+00  0.000000e+00       0.000000      0.000000   
25%         0.000000  0.000000e+00  0.000000e+00       0.000000      0.000000   
50%         0.000000  0.000000e+00  0.000000e+00       0.000000      0.000000   
75%         0.000000  5.600000e+02  1.123000e+02       0.000000      0.000000   
max    777330.090000  2.290329e+06  1.000230e+06  500000.000000  43129.070000   

          ...                 c11            c12           c13  primary_votes  \
count     ...         8213.000000    8213.000000  8.213000e+03   8.213000e+03   
mean      ...         1143.413799     426.940119  5.740178e+05   2.512320e+04   
std       ...        10712.754826    4125.721165  1.821689e+06   8.325324e+04   
min       ...            0.000000       0.000000 -4.920380e+04   0.000000e+00   
25%       ...            0.000000       0.000000  0.000000e+00   0.000000e+00   
50%       ...            0.000000       0.000000  9.600590e+03   4.928000e+03   
75%       ...            0.000000       0.000000  4.678489e+05   2.965800e+04   
max       ...       407000.000000  117400.000000  3.563831e+07   2.566298e+06   

        runoff_votes  general_votes  ge_runoff_election_votes   total_votes  \
count    8213.000000   8.213000e+03              8.213000e+03  8.213000e+03   
mean      412.211616   1.229814e+05              3.714814e+02  1.488883e+05   
std      8613.271191   3.243593e+05              1.713239e+04  3.976238e+05   
min         0.000000   2.000000e+00              0.000000e+00  7.000000e+00   
25%         0.000000   9.344000e+03              0.000000e+00  9.528000e+03   
50%         0.000000   7.899600e+04              0.000000e+00  9.256500e+04   
75%         0.000000   1.372530e+05              0.000000e+00  1.680910e+05   
max    631812.000000   7.864624e+06              1.228033e+06  1.025745e+07   

         totalspend     costvote  
count  8.213000e+03  8213.000000  
mean   8.521735e+05    12.816361  
std    2.149711e+06    54.032865  
min    0.000000e+00     0.000000  
25%    0.000000e+00     0.000000  
50%    1.874277e+05     1.791971  
75%    9.455734e+05     6.660852  
max    4.955574e+07   903.637692  

[8 rows x 21 columns]

In [30]:
df.count()

cand_id                     8213
cycle                       8213
c1                          8213
c2                          8213
c3                          8213
c4                          8213
c5                          8213
c6                          8213
c7                          8213
c8                          8213
c9                          8213
c10                         8213
c11                         8213
c12                         8213
c13                         8213
state_abbreviation          8213
district                    8186
incumbent                   8213
party                       8213
primary_votes               8213
runoff_votes                8213
general_votes               8213
ge_runoff_election_votes    8213
winner                      8213
total_votes                 8213
totalspend                  8213
costvote                    8213
dtype: int64

In [97]:
df.groupby('cycle').count()

cand_id    c1    c2    c3    c4    c5    c6    c7    c8    c9  \
cycle                                                                  
2004      1376  1376  1376  1376  1376  1376  1376  1376  1376  1376   
2006      1337  1337  1337  1337  1337  1337  1337  1337  1337  1337   
2008      1324  1324  1324  1324  1324  1324  1324  1324  1324  1324   
2010      1559  1559  1559  1559  1559  1559  1559  1559  1559  1559   
2012      1418  1418  1418  1418  1418  1418  1418  1418  1418  1418   
2014      1199  1199  1199  1199  1199  1199  1199  1199  1199  1199   

         ...     incumbent  party  primary_votes  runoff_votes  general_votes  \
cycle    ...                                                                    
2004     ...          1376   1376           1376          1376           1376   
2006     ...          1337   1337           1337          1337           1337   
2008     ...          1324   1324           1324          1324           1324   
2010     ...          1559   1559           1559          1559           1559   
2012     ...          1418   1418           1418          1418           1418   
2014     ...          1199   1199           1199          1199           1199   

       ge_runoff_election_votes  winner  total_votes  totalspend  costvote  
cycle                                                                       
2004                       1376    1376         1376        1376      1376  
2006                       1337    1337         1337        1337      1337  
2008                       1324    1324         1324        1324      1324  
2010                       1559    1559         1559        1559      1559  
2012                       1418    1418         1418        1418      1418  
2014                       1199    1199         1199        1199      1199  

[6 rows x 26 columns]

In [75]:
winner= df[df['winner'].isin(['1'])]

In [100]:
loser= df[df['winner'].isin(['0'])]

In [7]:
#load_digits(?)
from sklearn.datasets import load_digits 
digits = load_digits()
X = digits.data # X.shape == (n_samples, n_features) 
y = digits.target
print (X, y)

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]] [0 1 2 ..., 8 9 8]


In [10]:
#fit/estimator
def fit(self, X, y=None):
        """Fits estimator to data. """
        # set state of ``self``
        return self
print (fit)

<function fit at 0x11042fae8>


In [17]:
#predict
def predict(self, X):
        """Predict response of ``X``. """
        # compute predictions ``pred``
        return pred

In [44]:
#run fit, predict(?)
X=8213
y=26


In [47]:
#from sklearn import svm
#estimator = svm.SVC(gamma=0.001)
#estimator.fit(X, y)
#estimator.predict(x)

In [116]:
from sklearn.model_selection import train_test_split as tts 

X = df[[
    'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13'
]]
y = df['costvote']

print(X.shape)
print(y.shape)

(8213, 13)
(8213,)


In [117]:
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2)

In [118]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit ([[0, 0], [1, 1], [2, 2]], [0, 1, 2])

reg.coef_

array([ 0.5,  0.5])

In [119]:
# Ordinary least squares
from sklearn import linear_model
reg = linear_model.Ridge (alpha = .5)
reg.fit ([[0, 0], [0, 0], [1, 1]], [0, .1, 1]) 


reg.coef_

reg.intercept_ 

0.13636363636363641

In [120]:
# Ridge regression
from sklearn import linear_model
reg = linear_model.RidgeCV(alphas=[0.1, 1.0, 10.0])
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])       


reg.alpha_  

0.10000000000000001

In [121]:
# lasso
from sklearn import linear_model
reg = linear_model.Lasso(alpha = 0.1)
reg.fit([[0, 0], [1, 1]], [0, 1])



reg.predict([[1, 1]])

array([ 0.8])

In [122]:
# LARS lasso
from sklearn import linear_model
reg = linear_model.LassoLars(alpha=.1)
reg.fit([[0, 0], [1, 1]], [0, 1])  



reg.coef_  

array([ 0.71715729,  0.        ])

In [123]:
# Baysian Ridge Regression
from sklearn import linear_model
X = [[0., 0.], [1., 1.], [2., 2.], [3., 3.]]
Y = [0., 1., 2., 3.]
reg = linear_model.BayesianRidge()
reg.fit(X, Y)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

In [124]:
# Predict new values
reg.predict ([[1, 0.]])

array([ 0.50000013])

In [125]:
# weights of the model
reg.coef_

array([ 0.49999993,  0.49999993])

In [126]:
# Support vector machine
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [127]:
# SVM predictions
clf.predict([[2., 2.]])

array([1])

In [128]:
# Stochastic Gradient Descent
from sklearn.linear_model import SGDClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = SGDClassifier(loss="hinge", penalty="l2")
clf.fit(X, y)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', n_iter=5, n_jobs=1,
       penalty='l2', power_t=0.5, random_state=None, shuffle=True,
       verbose=0, warm_start=False)

In [129]:
# Predict new values
clf.predict([[2., 2.]])

array([1])